name: QA Automation Assessment

on:
  push:
  pull_request:

jobs:
  api_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx cypress run
      - uses: actions/upload-artifact@v4
        with:
          name: api-tests-report
          path: api-tests/cypress/reports

  e2e_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx cypress run
      - uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-report
          path: e2e-tests/cypress/reports

  mobile_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: npm ci
      - run: npx appium driver install fake
      - run: nohup npx appium server --log-level info &
      - run: npx wdio run wdio.conf.js
      - uses: actions/upload-artifact@v4
        with:
          name: mobile-tests-report
          path: mobile-tests/reports

  load_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: load-tests
    steps:
      - uses: actions/checkout@v4
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter
      - name: Run JMeter
        run: |
          jmeter -n -t jmeter-test-plan.jmx -l results.jtl -e -o report
      - uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: load-tests/report
